// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "!WQQOPOOOOOO'#C^'#C^OYOPO'#C`OOOO'#Ca'#CaQQOPOOQOOOOOOOOO,58x,58xOOOO-E6_-E6_PbOPO'#C^",
  stateData: "g~ORQOVPO~OVUOUSX~OVUO~O",
  goto: "eUPPVPZ_TROSTTOSQSORVS",
  nodeNames: "⚠ Document Line LineContent LastLine",
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData:
    "!_~RVOYhYZ!SZ]h]^!X^;'Sh;'S;=`|<%lOh~mTR~OYhZ]h^;'Sh;'S;=`|<%lOh~!PP;=`<%lh~!XOV~~![PYZ!S",
  tokenizers: [0],
  topRules: { Document: [0, 1] },
  tokenPrec: 0,
});
